export const PATH_ROUTE = {
  root: "/",
  home: "/home",
  dashboard: "/thong-ke",
  patientRegister: "/dang-ky-benh-nhan",
  doctorRegister: "/dang-ki-bac-si",
  revokeDoctor: "/thu-hoi-quyen",
  detailPatient: "/benh-nhan/:_addr",
  editPaitient: "/chinh-sua-benh-nhan",
  acceptDoctor: "/cap-quyen",
  detailDoctor: "/bac-si/:_addr",
  editDoctor: "/chinh-sua-bac-si",
  booking: "/tao-lich-hen",
  updateBooking: "/chinh-sua-lich-hen",
  listRecord: "/danh-sach-benh-nhan",
  listDoctor: "/danh-sach-bac-si",
  listBooking: "/danh-sach-cuoc-hen",
  detailBooking: "/lich-hen/:_addr",
};
